services:
    ur3e_ws:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                MAKEFLAGS: -j4
                PARALLELWORKERS: 4
        container_name: ur3e_humble_container
        environment:
            # to transport X11 application window
            - DISPLAY=$DISPLAY
            - QT_X11_NO_MITSHM=1
        volumes:
            # for USB devices
            - /dev:/dev
            # to tansport X11 application (require xhost local:)
            - /tmp/.X11-unix:/tmp/.X11-unix:rw
            # ros catkin dir
            - ./ros2_ws/src/ur3e_tutorials_py:/root/ros2_ws/src/ur3e_tutorials_py
            - ./ros2_ws/src/ur3e_tutorials_cpp:/root/ros2_ws/src/ur3e_tutorials_cpp
        privileged: true
        tty: true
        network_mode: host
        command: bash -c "source /opt/ros/humble/setup.bash && cd /root/ros2_ws && colcon build --executor parallel --parallel-workers 4 --symlink-install --mixin release && source /root/ros2_ws/install/setup.bash && bash"
